### ISSUE TITLE
Feature: implement v2 feed API

### ISSUE THREAD

**Issue by billglover** [billglover/starling#15]
The v2 feed API is now available for testing in the Sandbox and includes the following endpoints:
* `/api/v2/feed/account/{accountUid}/category/{categoryUid}`
* `/api/v2/feed/account/{accountUid}/category/{categoryUid}/{feedItemUid}`

**Comment by billglover** [comment]
Discussion on Slack gives more details on the `{categoryUid}`.

> In the account endpoints, one of the fields you get back is “defaultCategory”.
>
> – Sam Rose

Further explanation gives a clue as to how savings goals are implemented at Starling.

> Categories are essentially a sub-division of an account. The current major use of them is savings goals, so I believe you should also be able to put a savings goal uid in there and it’ll work as you might expect. The default category is what you might think of as just the current account itself.
>
> – Sam Rose

**Comment by shymega** [comment]
Just found this library, and I'm testing it out. I just wanted to ask though, should this issue be closed now?

**Comment by billglover** [comment]
Note: the project is now four years old and I believe the Starling API has moved on significantly and so this client may no longer function. I will update the project to reflect this. See https://developer.starlingbank.com as a good starting point for Starling development.
