### ISSUE TITLE
Documentation doesn't make it clear that "{{ACCESS_TOKEN}}" needs to be substituted for real access token

### ISSUE THREAD

**Issue by billglover** [billglover/starling#40]
Either the example or the documentation should be amended to make it clearer that users need to provide their Starling access token here.

https://github.com/billglover/starling/blob/a40600f92020b16800af4bc7d2312e8c29a7b5fc/README.md#L64

**Comment by shymega** [comment]
#41 looks good, but my main confusion with trying out this library is the brackets used. To the untrained eye, it might indicate that you should put the access token *inside* the brackets. I haven't done that personally, although it's not working for me as of yet - doing more tests - but maybe that should be clarified in the README..?
